# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goat < Formula
  desc "goat"
  homepage ""
  version "0.1.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/inatonix/goat/releases/download/v0.1.10/goat_Darwin_arm64.tar.gz"
      sha256 "0e0b9939d812943471c6d225ecf7d7e6921d28c3721caefc7dff7c3bd26196e8"

      def install
        bin.install "goat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inatonix/goat/releases/download/v0.1.10/goat_Darwin_x86_64.tar.gz"
      sha256 "691e39891a08bdfad9b11e444cd1952297d67371e1eed3d8d4420ffcc25d6ae7"

      def install
        bin.install "goat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inatonix/goat/releases/download/v0.1.10/goat_Linux_arm64.tar.gz"
      sha256 "5b9285d822541d4345d2ecad3e710808bd78688c933a1364a55c89f225beaa35"

      def install
        bin.install "goat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inatonix/goat/releases/download/v0.1.10/goat_Linux_x86_64.tar.gz"
      sha256 "9ebccf6fd5b1c11a02bce4ee8080d7f9be1e3d5d7f5c27ac25bcaf010a4d9cab"

      def install
        bin.install "goat"
      end
    end
  end
end
